### ISSUE TITLE
Add support for select diferent query port

### ISSUE THREAD

**Issue by raymand211092** [a-sync/game-server-watcher#10]
For example for teamspeak, for my used quero port 10101

**Comment by a-sync** [comment]
hey,
pushed an update that introduces all the available gamedig options in the config editor.
now you should be able to select teamspeakQueryPort from the optional properties:
![image](https://github.com/a-sync/game-server-watcher/assets/14183614/c4eb1988-07a0-47b5-991f-38e6eae43a65)
