### ISSUE TITLE
[PalWorld] Query Error

### ISSUE THREAD

**Issue by ThesiiNCey** [a-sync/game-server-watcher#13]
Hey i updated the GSW to the latest Version for Palworld this has added to gamedig support list but i cant Query the Server with Correct data all my other servers are Working

With www.battlemetrics.com its working to Query the Server with same data

System: Debian 12 GSW Running in Pterodactyl
All needed ports Open

**Comment by a-sync** [comment]
hey.
it seems like the palworld update was not yet released for gamedig v4! (not pushed to npm registry)

for the time being you can use the [gamedig-next branch of gsw](https://github.com/a-sync/game-server-watcher/tree/gamedig-next) which is an experimental version that has the latest gamedig source set as its dependency.
**But please beware, that gamedig has changed some of the game type IDs in the latest release, so you might need to update the game type for some existing servers!**

If/when gamedig releases the changes under the v4 version, the current gsw can be updated. (reinstall server in ptero)

**Comment by a-sync** [comment]
just for the record to make the pterodacty egg use a specific branch you need to find and edit the egg install script line that starts with `git clone https:` and replace it with:
`git clone -b gamedig-next https:`

**Comment by treemlt** [comment]
I edit the egg.json but i still don't see the game

https://pastebin.com/Pac1KKTq

**Comment by iamc0ke** [comment]
Worked for me thanks :)

**Comment by a-sync** [comment]
> I edit the egg.json but i still don't see the game
> 
> https://pastebin.com/Pac1KKTq
@treemlt it looks good to me. make sure you **create a new server** with the edited egg

**Comment by treemlt** [comment]
> > I edit the egg.json but i still don't see the game
> > https://pastebin.com/Pac1KKTq
> 
> @treemlt it looks good to me. make sure you **create a new server** with the edited egg

I managed to make it work :) thanks
