### ISSUE TITLE
Update Gamedig

### ISSUE THREAD

**Issue by scarecr0w12** [a-sync/game-server-watcher#14]
Can you update this to support the new GameDig 5 Beta? It supports Palworld and would be huge to have that added to this.

**Comment by a-sync** [comment]
Hey.  
I already implemented the necessary changes, please check out the gamedig-next branch if you want to use it right away: https://github.com/a-sync/game-server-watcher/tree/gamedig-next  
As soon as gamedig releases a stable v5 i will merge the changes to the master branch.

If you're using pterodactyl, to make the pterodacty egg use a specific branch you need to find and edit the egg install script line that starts with `git clone https:` and replace it with:
`git clone -b gamedig-next https:` then install on a new server. (Or switch branch/update files directly inside the server and rebuild sources)

**Comment by scarecr0w12** [comment]
This does not work. the Gamedig-next only has 4.3 version, and the v5 beta requires extensive changes to your code, example:

```
[Pterodactyl Daemon]: Finished pulling Docker container image
v20.11.0
:/home/container$ env PORT=${SERVER_PORT} /usr/local/bin/node --experimental-modules /home/container/dist/server.js
/home/container/dist/server.js:11
const gamedig_1 = require("gamedig");
                  ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/container/node_modules/gamedig/lib/index.js from /home/container/dist/server.js not supported.
Instead change the require of index.js in /home/container/dist/server.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/container/dist/server.js:11:19) {
  code: 'ERR_REQUIRE_ESM'
}
Node.js v20.11.0
```

**Comment by scarecr0w12** [comment]
Unless something didn't update i suppose taking a look at the actual repo files directly

**Comment by scarecr0w12** [comment]
Ok yeah all my fault, i didn't read what you put fully. all good.
