### ISSUE TITLE
Palworld server

### ISSUE THREAD

**Issue by treemlt** [a-sync/game-server-watcher#17]
I am trying to add a palworld server but there is no option for that

**Comment by iamc0ke** [comment]
Same. It seems like the newest node-GameDig - Game Server Query Library is not beeing used.

**Comment by a-sync** [comment]
until gamedig v5 is still beta you can use the gamedig-next branch: https://github.com/a-sync/game-server-watcher/tree/gamedig-next

once gamedig releases the stable v5 i will merge the changes to the master branch.
if you guys are using pterodactyl, here are the instructions on how to switch to a specific branch: https://github.com/a-sync/game-server-watcher/issues/13#issuecomment-1902678883

**Comment by iamc0ke** [comment]
Worked for me thank you!
