### ISSUE TITLE
Problem with cloudnode publishing

### ISSUE THREAD

**Issue by pwlgrzs** [a-sync/game-server-watcher#2]
Good day, I wanted to try publishing to the cloudnode but I am having some issues.
Firstly, readme states to use CLOUDNODE_REPO_URL secret to store URL but publish.yml seems to use CLOUD_REPO_URL, I think this needs to be updated if I am right.
Then, when changed CLOUDNDOE_REPO_URL to CLOUD_REPO_URL I am getting following error when running action:

Run git remote add cloudnode ***
error: src refspec cloud does not match any
error: failed to push some refs to 'https://git.cloudno.de/git/pwlgrzs/<redacted>git'
Error: Process completed with exit code 1.

Could you please help me debug? Thanks!

**Comment by pwlgrzs** [comment]
Okay, I should have published to cloud branch, but I am still having an issue here:

error: RPC failed; HTTP 504 curl 22 The requested URL returned error: 504
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date
Error: Process completed with exit code 1.

**Comment by pwlgrzs** [comment]
It finally started as it should, must have been something between GitHub and Cloudnode.

**Comment by a-sync** [comment]
hey, thx for reporting the typo in the wiki 👍 
on the RPC error: i think you are right. i have seen the same yesterday, but regardless the error the changes got pushed to cloudno.de
