### ISSUE TITLE
Feature: Custom description text box

### ISSUE THREAD

**Issue by Rephot** [a-sync/game-server-watcher#20]
HI,

I was wondering if you could implement a short description text box, this way i can add some instructions for things like modpacks/connection instructions or passwords into the widget on my discord server

Cheers,
Rephot

**Comment by a-sync** [comment]
hey,
implemented your idea on the [gamedig-next](https://github.com/a-sync/game-server-watcher/tree/gamedig-next) branch. (There are plans to make the embed fields completely customizable for each channel in the future, but for now i just added a server "Description" field, and inserted it between the server infos and the player list.) 
Here is how it looks:

![desc editor](https://github.com/a-sync/game-server-watcher/assets/14183614/6eba3592-8955-4372-8ba9-4035606e5df4)

![discord embed](https://github.com/a-sync/game-server-watcher/assets/14183614/1ae99fe3-a95a-4887-883d-ed495e167356)

I hope this is what you had in mind. Lmk what you think :)

**Comment by Rephot** [comment]
Works perfect! Thank you
